name: pt
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astroid=2.11.7=py310h06a4308_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.1=py310h9ce1e76_0
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.7.99=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - flake8=4.0.1=pyhd3eb1b0_1
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.4.0.31=0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - importlib-metadata=4.11.3=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - isort=5.9.3=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py310h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.3=h295c915_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.3.0.22=0
  - numpy=1.23.3=py310hd5efca6_1
  - numpy-base=1.23.3=py310h8e6c178_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - pillow=9.2.0=py310hace64e9_1
  - pip=22.2.2=py310h06a4308_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pylint=2.14.5=py310h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.6=haa1d7c7_1
  - pytorch=1.13.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h67b0de4_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - tomlkit=0.11.1=py310h06a4308_0
  - torchaudio=0.13.0=py310_cu117
  - torchvision=0.14.0=py310_cu117
  - typing_extensions=4.3.0=py310h06a4308_0
  - tzdata=2022f=h04d1e81_0
  - urllib3=1.26.12=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xz=5.2.6=h5eee18b_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zipp=3.8.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - autokeras==1.0.20
    - babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - chardet==4.0.0
    - clip-anytorch==2.5.0
    - contourpy==1.0.6
    - cycler==0.11.0
    - datasets==2.7.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - einops==0.6.0
    - entrypoints==0.4
    - etils==0.9.0
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - fire==0.4.0
    - flatbuffers==22.10.26
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - gast==0.4.0
    - geotorch==0.3.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.4
    - grpcio==1.50.0
    - h5py==3.7.0
    - huggingface-hub==0.10.1
    - idna==2.10
    - imageio==2.22.4
    - importlib-resources==5.10.0
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.10
    - jsonschema==4.17.0
    - jupyter-client==7.4.4
    - jupyter-core==5.0.0
    - jupyter-server==1.23.1
    - jupyterlab==3.5.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.16.2
    - jupyterlab-widgets==3.0.3
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - keras-tuner==1.1.3
    - kiwisolver==1.4.4
    - kt-legacy==1.0.4
    - libclang==14.0.6
    - lightning-utilities==0.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - multidict==6.0.2
    - multiprocess==0.70.13
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.4
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - oauthlib==3.2.2
    - opencv-python-headless==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.3
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.32
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==10.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - python-dotenv==0.21.0
    - pytorch-lightning==1.8.1
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qudida==0.0.4
    - regex==2022.10.31
    - requests==2.25.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.9
    - ruff==0.0.108
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-datasets==4.7.0
    - tensorflow-estimator==2.10.0
    - tensorflow-hub==0.12.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-metadata==1.10.0
    - termcolor==2.1.0
    - terminado==0.17.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - toml==0.10.2
    - torchmetrics==0.10.3
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - transformers==4.24.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - xxhash==3.1.0
    - yarl==1.8.1
prefix: /local/home/edebenedetti/miniconda3/envs/pt
